# Main page
[[pages]]
path = "pages/HOME.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/Path_Editor.py"
name = "Path Editor"
icon = "ğŸ—‚ï¸"

[[pages]]
path = "pages/Column Consolidation App.py"
name = "Column Consolidation"
icon = "ğŸ“Š"

[[pages]]
path = "pages/Country Code Finder.py"
name = "Country Code Finder"
icon = "ğŸŒ"

[[pages]]
path = "pages/Date_Range_Finder.py"
name = "Date Range Finder"
icon = "ğŸ“…"

[[pages]]
path = "pages/Paid_Media_Spends_Vars.py"
name = "Paid Media Spends Variables"
icon = "ğŸ’¸"

[[pages]]
path = "pages/Hyperparameters.py"
name = "Hyperparameters"
icon = "âš™ï¸"

[[pages]]
path = "pages/Sub_Model_Analysis.py"
name = "Sub Model Analysis"
icon = "ğŸ”"

[[pages]]
path = "pages/Actual VS Predicted.py"
name = "Actual vs Predicted"
icon = "ğŸ“‰"

[[pages]]
path = "pages/Aggregated Spend Data by Channel.py"
name = "Spends by Channel"
icon = "ğŸ“Š"

[[pages]]
path = "pages/Spends by creative.py"
name = "Spends by Creative"
icon = "ğŸ¨"


[[pages]]
path = "pages/Aggregated Website Visits Data by Channel.py"
name = "Visits by Channel"
icon = "ğŸšª"

[[pages]]
path = "pages/Website visit by creative.py"
name = "Visits by Creative"
icon = "ğŸ–¼ï¸"

[[pages]]
path = "pages/Cost Per Visit by Creative.py"
name = "CPV by Creative"
icon = "ğŸ’µ"

[[pages]]
path = "pages/Cost Per Visit.py"
name = "Cost Per Visit"
icon = "ğŸ§®"

[[pages]]
path = "pages/Aggregated Website Conversions Data by Channel.py"
name = "Conversions by Channel"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/Website conversions by creative.py"
name = "Conversions by Creative"
icon = "ğŸ–Œï¸"

[[pages]]
path = "pages/Cost Per Conversion by Creative.py"
name = "CPC by Creative"
icon = "ğŸ’²"

[[pages]]
path = "pages/Cost Per Conversion.py"
name = "Cost Per Conversion"
icon = "ğŸ§®"

[[pages]]
path = "pages/Share of spends by placements.py"
name = "Share of Spends"
icon = "ğŸ“‹"

[[pages]]
path = "pages/Model KPI Calculater.py"
name = "Model KPI Calculator"
icon = "ğŸ§®"

[[pages]]
path = "pages/Effect and Spend share.py"
name = "Effect & Spend Share"
icon = "âš–ï¸"

[[pages]]
path = "pages/trial.py"
name = "Trial Page"
icon = "ğŸ”¬"
