# Main page
[[pages]]
path = "home.py"
name = "Home"
icon = "ğŸ "

# Section 1: Robyn Code
[[pages]]
name = "Robyn Code"
icon = "ğŸ”§"
is_section = true

[[pages]]
path = "pages/Path_Editor.py"
name = "Path Editor"
icon = "ğŸ—‚ï¸"

[[pages]]
path = "pages/Column_Consolidation_App.py"
name = "Column Consolidation"
icon = "ğŸ“Š"

[[pages]]
path = "pages/Country_Code_Finder.py"
name = "Country Code Finder"
icon = "ğŸŒ"

[[pages]]
path = "pages/Date_Range_Finder.py"
name = "Date Range Finder"
icon = "ğŸ“…"

[[pages]]
path = "pages/Paid_Media_Spends_Vars.py"
name = "Paid Media Spends"
icon = "ğŸ’¸"

[[pages]]
path = "pages/Hyperparameters.py"
name = "Hyperparameters"
icon = "âš™ï¸"

# Section 2: Model Selection
[[pages]]
name = "Model Selection"
icon = "ğŸ“ˆ"
is_section = true

[[pages]]
path = "pages/Sub_Model_Analysis.py"
name = "Sub Model Analysis"
icon = "ğŸ”"

[[pages]]
path = "pages/Actual_VS_Predicted.py"
name = "Actual vs Predicted"
icon = "ğŸ“‰"

# Section 3: Spends
[[pages]]
name = "Spends"
icon = "ğŸ’°"
is_section = true

[[pages]]
path = "pages/Aggregated_Spend_Data_by_Channel.py"
name = "Spends by Channel"
icon = "ğŸ“Š"

[[pages]]
path = "pages/Spends_by_creative.py"
name = "Spends by Creative"
icon = "ğŸ¨"

# Section 4: Website Visits
[[pages]]
name = "Website Visits"
icon = "ğŸ‘ï¸"
is_section = true

[[pages]]
path = "pages/Aggregated_Website_Visits_Data_by_Channel.py"
name = "Visits by Channel"
icon = "ğŸšª"

[[pages]]
path = "pages/Website_visit_by_creative.py"
name = "Visits by Creative"
icon = "ğŸ–¼ï¸"

[[pages]]
path = "pages/Cost_Per_Visit_by_Creative.py"
name = "CPV by Creative"
icon = "ğŸ’µ"

[[pages]]
path = "pages/Cost_Per_Visit.py"
name = "Cost Per Visit"
icon = "ğŸ§®"

# Section 5: Conversions
[[pages]]
name = "Conversions"
icon = "ğŸ”„"
is_section = true

[[pages]]
path = "pages/Aggregated_Website_Conversions_Data_by_Channel.py"
name = "Conversions by Channel"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/Website_conversions_by_creative.py"
name = "Conversions by Creative"
icon = "ğŸ–Œï¸"

[[pages]]
path = "pages/Cost_Per_Conversion_by_Creative.py"
name = "CPC by Creative"
icon = "ğŸ’²"

[[pages]]
path = "pages/Cost_Per_Conversion.py"
name = "Cost Per Conversion"
icon = "ğŸ§®"

# Section 6: Presentation
[[pages]]
name = "Presentation"
icon = "ğŸ“‘"
is_section = true

[[pages]]
path = "pages/Share_of_spends_by_placements.py"
name = "Share of Spends"
icon = "ğŸ“‹"

[[pages]]
path = "pages/Model_KPI_Calculater.py"
name = "Model KPI Calculator"
icon = "ğŸ§®"

[[pages]]
path = "pages/Effect_and_Spend_share.py"
name = "Effect & Spend Share"
icon = "âš–ï¸"

# Section 7: Trial
[[pages]]
name = "Trial"
icon = "ğŸ§ª"
is_section = true

[[pages]]
path = "pages/trial.py"
name = "Trial Page"
icon = "ğŸ”¬"
