# Main page
[[pages]]
path = "pages/HOME.py"
name = "Home"
icon = "ğŸ "

# Section 1: Robyn Code
[[pages]]
name = "Section 1: Robyn Code"
icon = ""
is_section = true

[[pages]]
path = "pages/Path_Editor.py"
name = "Path Editor"
icon = "ğŸ—‚ï¸"

[[pages]]
path = "pages/Country Code Finder.py"
name = "Country Code Finder"
icon = "ğŸŒ"

[[pages]]
path = "pages/Robyn Code Processing.py"
name = "Code Processing"
icon = "âš™ï¸"

# Section 2: Model Selection
[[pages]]
name = "Section 2: Model Selection"
icon = ""
is_section = true

[[pages]]
path = "pages/Sub_Model_Analysis.py"
name = "Sub Model Analysis"
icon = "ğŸ”"

[[pages]]
path = "pages/Actual VS Predicted.py"
name = "Actual vs Predicted"
icon = "ğŸ“‰"

# Section 3: Spends
[[pages]]
name = "Section 3: Spends"
icon = ""
is_section = true

[[pages]]
path = "pages/Spends.py"
name = "Spends by Channel/Creative/Format"
icon = "ğŸ’°"

# Section 4: Website Visits
[[pages]]
name = "Section 4: Website Visits"
icon = ""
is_section = true

[[pages]]
path = "pages/website_visits_analysis.py"
name = "Visits by Channel/Creative/Format"
icon = "ğŸ“ "

[[pages]]
path = "pages/cpv_analysis.py"
name = "Cost Per Visit Analysis"
icon = "ğŸŒ"

# Section 5: Conversions
[[pages]]
name = "Section 5: Conversions"
icon = ""
is_section = true

[[pages]]
path = "pages/Aggregated Website Conversions Data by Channel.py"
name = "Conversions by Channel"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/Website conversions by creative.py"
name = "Conversions by Creative"
icon = "ğŸ–Œï¸"

[[pages]]
path = "pages/Cost Per Conversion by Creative.py"
name = "CPC by Creative"
icon = "ğŸ’²"

[[pages]]
path = "pages/Cost Per Conversion.py"
name = "Cost Per Conversion"
icon = "ğŸ§®"

# Section 6: Presentation
[[pages]]
name = "Section 6: Presentation"
icon = ""
is_section = true

[[pages]]
path = "pages/Share of spends by placements.py"
name = "Share of Spends"
icon = "ğŸ“‹"

[[pages]]
path = "pages/Model KPI Calculater.py"
name = "Model KPI Calculator"
icon = "ğŸ§®"

[[pages]]
path = "pages/Effect and Spend share.py"
name = "Effect & Spend Share"
icon = "âš–ï¸"

# Section 7: Optimization
[[pages]]
name = "Section 7: Optimization"
icon = ""
is_section = true

[[pages]]
path = "pages/Optimization.py"
name = "Optimization Page"
icon = "ğŸ¤–"

# Section 8: Trial
[[pages]]
name = "Trial"
icon = ""
is_section = true

[[pages]]
path = "pages/trial.py"
name = "Trial Page"
icon = "ğŸ”¬"

[[pages]]
path = "pages/CPA.py"
name = "CPA"
icon = "ğŸ”¬"
